services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181" 
    networks:
      - internal
      - public
      
  zoonavigator:
    image: elkozmon/zoonavigator
    container_name: zoonavigator
    ports:
      - "9000:9000"
    depends_on: 
      - zookeeper
    networks:
      - internal
      - public
      
  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    ports:
      - "19092:19092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_LISTENERS: INTERNAL_LISTENER://kafka-1:9092,PUBLIC_LISTENER://0.0.0.0:29092,EXTERNAL_LISTENER://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_LISTENER://kafka-1.internal:9092,PUBLIC_LISTENER://kafka-1.public:29092,EXTERNAL_LISTENER://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_LISTENER:PLAINTEXT,PUBLIC_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
    networks:
      - internal
      - public
      
  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    ports:
      - "19093:19093"
      - "29093:29093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_LISTENERS: INTERNAL_LISTENER://kafka-2:9092,PUBLIC_LISTENER://0.0.0.0:29093,EXTERNAL_LISTENER://0.0.0.0:19093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_LISTENER://kafka-2.internal:9092,PUBLIC_LISTENER://kafka-2.public:29093,EXTERNAL_LISTENER://localhost:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_LISTENER:PLAINTEXT,PUBLIC_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
    networks:
      - internal
      - public
      
  kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-3
    ports:
      - "19094:19094"
      - "29094:29094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_LISTENERS: INTERNAL_LISTENER://kafka-3:9092,PUBLIC_LISTENER://0.0.0.0:29094,EXTERNAL_LISTENER://0.0.0.0:19094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_LISTENER://kafka-3.internal:9092,PUBLIC_LISTENER://kafka-3.public:29094,EXTERNAL_LISTENER://localhost:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_LISTENER:PLAINTEXT,PUBLIC_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
    networks:
      - internal
      - public
      
  test-web-client:
    image: test-web-client
    container_name: foo
    build:
      context: .
      dockerfile: Distributed.Replication.Kafka.TestWebClient/Dockerfile
      
networks:
  public:
    name: public
    driver: bridge
    attachable: true
  internal:
    name: internal
    driver: bridge